defaults:
  - model: xsmall

name: MegaMolBART
do_training: True # set to false if data preprocessing steps must be completed
do_testing: False # set to true to run evaluation on test data after training, requires test_dataset section
seed: 42
restore_from_path: null # used when starting from a .nemo file

trainer:
  devices: 1
  num_nodes: 1
  accelerator: gpu
  precision: 16
  logger: False # logger provided by exp_manager
  enable_checkpointing: False # checkpointing done by exp_manager
  replace_sampler_ddp: False
  max_epochs: null
  max_steps: 100000 # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 200
  val_check_interval: 100
  num_sanity_val_steps: 2 # set to 0 or small number to test validation before completing a full epoch
  limit_val_batches: 10
  limit_test_batches: 0
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

exp_manager:
  name: ${name}
  exp_dir: /result/nemo_experiments/${.name}/${.wandb_logger_kwargs.name}
  explicit_log_dir: ${.exp_dir}
  create_wandb_logger: True
  create_tensorboard_logger: True
  wandb_logger_kwargs:
    project: ${model.name}_pretraining
    name: ${model.name}_pretraining
    group: ${model.name}
    job_type: Localhost_nodes_${trainer.num_nodes}_gpus_${trainer.devices}
    entity: clara-discovery
    notes: "date: ${now:%y%m%d-%H%M%S}"
    tags:
      - ${name}
      - ${model.name}
    offline: False
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_molecular_accuracy # TODO switch to molecular_accuracy when correctly calculated
    mode: max
    save_top_k: 3
    filename: '${name}-${model.name}--{val_molecular_accuracy:.2f}-{val_loss:.2f}-{step}-{consumed_samples}'
    model_parallel_size: ${multiply:${model.tensor_model_parallel_size}, ${model.pipeline_model_parallel_size}}
    always_save_nemo: False # saves nemo file during validation, not implemented for model parallel

model:
  name: xsmall_span_aug

  # model parallelism 
  micro_batch_size: 32
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1 # T5 PP is not supported yet. Use 1 for now.

  tokenizer:
    mask_scheme: span
    mask_prob: 0.1

  data:  
    dataset_path: /data/zinc_csv_split
    dataset_files: x[000..001].csv
    encoder_augment: True # consistent with DEFAULT_AUGMENT in AZ script
    encoder_mask: True # task = mask(span)_aug
    decoder_augment: True # task = mask(span)_aug
    decoder_mask: False
    micro_batch_size: ${model.micro_batch_size}
    num_workers: 10

  optim:
    name: fused_adam
    lr: 1.0 # max is scaled by Noam scheduler to d_model**(-0.5) * warmup**(-0.5)
    betas:
      - 0.9
      - 0.999
    eps: 1e-8
    weight_decay: 0.01
    sched:
      name: NoamAnnealing
      d_model: ${model.hidden_size}
      warmup_steps: null
      warmup_ratio: 0.008
      max_steps: ${trainer.max_steps}
      min_lr: 1e-5

