name: &name MegaMolBART
do_training: true # set to false to preprocess data
do_testing: false # set to true to run evaluation on test data after training

trainer:
  gpus: 2
  num_nodes: 1
  max_steps: 1000000
  accumulate_grad_batches: 1
  accelerator: ddp
  gradient_clip_val: 0.0
  checkpoint_callback: false # use exp_manager
  logger: false
  val_check_interval: 2
  # amp_level: O1 # O1/O2 for mixed precision
  # precision: 16 # Should be set to 16 for O1 and O2, default is 16 as PT ignores it when am_level is O0

tokenizer:
  vocab_path: /code/NeMo/nemo/collections/chem/vocab/megamolbart_pretrain_vocab.txt

model:
  name: *name
  d_model: 256 # hidden_size
  num_layers: 4
  num_heads: 8
  d_feedforward: 1024 # 4 * hidden_size
  max_seq_len: 512
  dropout: 0.1
  pretrained: false
  checkpoint_file: null # /path/to/megatron/checkpoint/model_optim_rng.pt

  train_ds:
    filepath: /result/zinc_csv/train/x[000..001].csv
    pin_memory: false 
    batch_size: 8
    shuffle: false
    drop_last: false
    num_workers: 8

  validation_ds:
    filepath: /result/zinc_csv/val/x[000..001].csv
    pin_memory: false 
    batch_size: 8
    shuffle: false
    drop_last: false
    num_workers: 8

  # TODO verify that optimizer and scheduler params set correctly
  optim:
    name: adam
    lr: 0.003
    weight_decay: 0.0
    betas: [0.9, 0.999]
    sched:
      name: CosineAnnealing
      warmup_steps: null
      warmup_ratio: 0.01 # warmup
      min_lr: 1.0e-5
      last_epoch: -1
      max_steps: 110000
      monitor: loss
      reduce_on_plateau: false

exp_manager:
  exp_dir: /result/nemo_experiments  # exp_dir for experiment, defaults to "./nemo_experiments"
  name: *name
  create_tensorboard_logger: true
  resume_ignore_no_checkpoint: true
  resume_if_exists: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    always_save_nemo: true
    save_top_k: 1
    mode: max
  create_wandb_logger: true
  wandb_logger_kwargs:
    name: db
    project: *name