defaults:
  - dataset_defaults

encoder_augment: true # consistent with DEFAULT_AUGMENT in AZ script
encoder_mask: false
decoder_augment: false
canonicalize_target_smiles: false # consistent with setting in AZ script
